### PR TITLE
Added bootstrap for css layout

### PR DESCRIPTION
**Pull request by DtheC**
I’ve added in bootstrap (http://getbootstrap.com) and tweaked the layout slightly so that the page is now responsive (and works on mobile!).

### CODE REVIEW

**Comment by DtheC** [comment]
Hope this isn't overstepping! I've not actually contributed to a public github project before.

**Comment by st33d** [comment]
I'm designing this to work on my iPad. The key features being able to select options from the folders on the left and read on the right. So anything that makes it not work on my iPad I'm generally going to not merge. I'm not sure how bootstrap retains the same functionality. Especially as I only got the scroll panes to work by nailing them to the center of the page.

I dunno - can you create a fork at all? I'd love to see what else the project can build into - but I really am going to be a pedant about my setup on iPad.

**Comment by DtheC** [comment]
Not sure what you mean by 'makes it not work with my iPad'- I tested on my iPad and it works perfectly in both landscape and portrait with bootstrap plus it makes it grow or shrink to fit any resolution so works fine on my iPhone, too.

**Comment by DtheC** [comment]
Ah wait- I think I understand. I didn't realise the menu scrolled with the page.

**Pull request closed without merging**
